CREATE TABLE Person (
	person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_name varchar(100) NOT NULL,
	year_of_birth int NOT NULL,
	email varchar(35) NOT NULL UNIQUE
);

CREATE TABLE Book (
	book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(100) NOT NULL,
	author varchar(100) NOT NULL,
	year int NOT NULL,
	person_id int REFERENCES Person(person_id) ON DELETE SET NULL
);